name: Array.iterator
author: cainrus
category: Native
tags: [array, iterator]
docs: http://github.com/cainrus/mootools-array-iterator/blob/master/README.md
demo: http://adava.ru/demo/mootools-array-iterator/index.html
